name: Build & Push Docker image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ecr-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: batm-staging-docker-image
  START_VERSION: 1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install jq (for version parsing)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Compute next version from ECR (patch bump)
        id: version
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        shell: bash
        run: |
          set -euo pipefail

          TAGS_JSON="$(aws ecr describe-images \
            --repository-name "${ECR_REPOSITORY}" \
            --query 'imageDetails[].imageTags' --output json 2>/dev/null || echo '[]')"

          HIGHEST="$(echo "${TAGS_JSON}" \
            | jq -r '
              [ .[]? | .[]? | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) ]
              | sort_by( split(".") | map(tonumber) )
              | last // empty
            ')"

          if [[ -z "${HIGHEST}" ]]; then
            NEXT="${START_VERSION}"
            echo "No numeric tags found, starting at ${NEXT}"
          else
            IFS='.' read -r MA MI PA <<< "${HIGHEST}"
            NEXT="${MA}.${MI}.$((PA+1))"
            echo "Highest existing tag: ${HIGHEST} -> next: ${NEXT}"
          fi

          if aws ecr list-images --repository-name "${ECR_REPOSITORY}" \
               --filter tagStatus=TAGGED --query 'imageIds[].imageTag' --output text \
               | grep -qx "${NEXT}"; then
            echo "Computed tag ${NEXT} already exists. Exiting to respect immutability." >&2
            exit 1
          fi

          echo "next=${NEXT}" >> "$GITHUB_OUTPUT"

      # Enable BuildKit/Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Unique digest metadata (keeps cache but makes a new image each run)
      - name: Compute build timestamp
        id: buildmeta
        run: echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

      # Build & push with persistent cache and unique labels
      - name: Build & Push (cached, unique digest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.version.outputs.next }}
          labels: |
            org.opencontainers.image.created=${{ steps.buildmeta.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.version.outputs.next }}
            org.opencontainers.image.source=${{ github.repository }}
          cache-from: type=gha,scope=ecr-main
          cache-to: type=gha,mode=max,scope=ecr-main
          provenance: false

      - name: Summary
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.version.outputs.next }}
        run: |
          echo "### Image pushed" >> $GITHUB_STEP_SUMMARY
          echo "- \`${ECR_REGISTRY}/${ECR_REPOSITORY}:${TAG}\`" >> $GITHUB_STEP_SUMMARY
      
# ---------- DEPLOY TO ECS ----------
      - name: Set ECS deploy vars
        env:
            CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}   # e.g. batm-sandbox-ecs-cluster (set in repo Variables)
            SERVICE_NAME: batm                       # ECS service name (from Terraform)
            TASK_FAMILY: batm                        # Task definition family
            CONTAINER_NAME: batm                     # Container name inside the task def
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
            TAG: ${{ steps.version.outputs.next }}
        run: |
            echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_ENV
            echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
            echo "TASK_FAMILY=${TASK_FAMILY}" >> $GITHUB_ENV
            echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
            echo "IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:${TAG}" >> $GITHUB_ENV

      - name: Render next task definition (inject new image)
        id: render-td
        run: |
            set -euo pipefail
            aws ecs describe-task-definition \
            --task-definition "$TASK_FAMILY" \
            --query 'taskDefinition' > td.json

            # Strip read-only fields and set the new image for the chosen container
            jq --arg img "$IMAGE" --arg name "$CONTAINER_NAME" '
            del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)
            | .containerDefinitions |= map(if .name==$name then (.image=$img) else . end)
            ' td.json > td.new.json

            echo "Rendered task def with image:"
            jq -r '.family, (.containerDefinitions[] | select(.name=="'"$CONTAINER_NAME"'").image)' td.new.json

      - name: Register new task definition revision
        id: register-td
        run: |
            set -euo pipefail
            NEW_TD_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://td.new.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
            echo "new_td_arn=${NEW_TD_ARN}" >> "$GITHUB_OUTPUT"
            echo "Registered: ${NEW_TD_ARN}"

      - name: Update ECS service to new task def
        run: |
            set -euo pipefail
            aws ecs update-service \
            --cluster  "$CLUSTER_NAME" \
            --service  "$SERVICE_NAME" \
            --task-definition "${{ steps.register-td.outputs.new_td_arn }}" \
            --force-new-deployment

      - name: Wait for service stable
        run: |
            set -euo pipefail
            aws ecs wait services-stable \
            --cluster "$CLUSTER_NAME" \
            --services "$SERVICE_NAME"

      - name: Deploy summary
        env:
            IMAGE: ${{ env.IMAGE }}
            TD_ARN: ${{ steps.register-td.outputs.new_td_arn }}
        run: |
            echo "### ECS Deploy" >> $GITHUB_STEP_SUMMARY
            echo "- Image: \`${IMAGE}\`" >> $GITHUB_STEP_SUMMARY
            echo "- Task def: \`${TD_ARN}\`" >> $GITHUB_STEP_SUMMARY


      - name: Notify Slack (incoming webhook)
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          TAG: ${{ steps.version.outputs.next }}
        run: |
          set -euo pipefail
          sudo apt-get update >/dev/null && sudo apt-get install -y jq >/dev/null
          IMAGE="${ECR_REGISTRY}/${ECR_REPOSITORY}:${TAG}"
          SHORT_SHA="${GITHUB_SHA::7}"
          RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

          payload=$(jq -n \
            --arg header ":whale: *Docker image pushed to ECR*" \
            --arg image "$IMAGE" \
            --arg tag "$TAG" \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg sha "$SHORT_SHA" \
            --arg run "$RUN_URL" \
            '{text:$header, blocks:[
              {type:"section", text:{type:"mrkdwn", text:$header}},
              {type:"section", fields:[
                {type:"mrkdwn", text:"*Image:*\n\($image)"},
                {type:"mrkdwn", text:"*Tag:*\n\($tag)"},
                {type:"mrkdwn", text:"*Repo:*\n\($repo)"},
                {type:"mrkdwn", text:"*Commit:*\n\($sha)"},
                {type:"mrkdwn", text:"*Workflow run:*\n\($run)"}
              ]}
            ]}')
          curl -X POST -H 'Content-type: application/json' \
               --data "$payload" "$SLACK_WEBHOOK_URL"